# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SupercamCompanion
                                 A QGIS plugin
 QGIS plugin for vizualisation of SuperCam data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-05
        copyright            : (C) 2023 by Baptiste Perrier
        email                : baptiste.perrier@ens-lyon.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SupercamCompanion class from file SupercamCompanion.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .supercam_companion import SupercamCompanion
    return SupercamCompanion(iface)
